### ISSUE TITLE
메뉴 collapse/extend를 자바스크립트에서 CSS로 대체

### ISSUE THREAD

**Issue by lens0021** [femiwiki/FemiwikiSkin#146]
## 현재 상황

`skins.femiwiki.js` 모듈에서 불러오는 [`resources/skins.femiwiki.js/collapsibleMenu.js` 파일](https://github.com/femiwiki/FemiwikiSkin/blob/44ab928/resources/skins.femiwiki.js/collapsibleMenu.js)에서 자바스크립트와 JQuery를 이용하여 처리 중입니다.

##  원하는 형태

벡터 스킨(v2)의 collapsible sidebar 처럼 합니다. 예시를 https://www.mediawiki.org/wiki/MediaWiki?useskinversion=2 에서 확인할 수 있습니다.

코드([원본](https://github.com/wikimedia/Vector/blob/master/resources/skins.vector.styles/Sidebar.less#L69)):
```less
.mw-checkbox-hack-checkbox:not( :checked ) ~ .mw-sidebar {
  // Turn off presentation so that screen readers get the same effect as visually hiding.
  // Visibility and opacity can be animated. If animation is unnecessary, use `display: none`
  // instead to avoid hidden rendering.
  visibility: hidden;
  opacity: 0;
  .transform( translateX( -100% ) );
}
```

## 참고

- https://phabricator.wikimedia.org/T246419
