### ISSUE TITLE
문서에서 lang=ja 설정해도 일본어 글꼴이 선택되지 않음

### ISSUE THREAD

**Issue by saschanaz** [femiwiki/FemiwikiSkin#228]
[프로젝트 세카이 컬러풀 스테이지! feat. 하츠네 미쿠/악곡/아이디스마일](https://femiwiki.com/w/%ED%94%84%EB%A1%9C%EC%A0%9D%ED%8A%B8_%EC%84%B8%EC%B9%B4%EC%9D%B4_%EC%BB%AC%EB%9F%AC%ED%92%80_%EC%8A%A4%ED%85%8C%EC%9D%B4%EC%A7%80!_feat._%ED%95%98%EC%B8%A0%EB%84%A4_%EB%AF%B8%EC%BF%A0/%EC%95%85%EA%B3%A1/%EC%95%84%EC%9D%B4%EB%94%94%EC%8A%A4%EB%A7%88%EC%9D%BC#.EA.B0.80.EC.82.AC) 문서에서 lang=ja를 선택해도 적절한 일본어 글꼴이 선택되지 않습니다.

https://github.com/femiwiki/FemiwikiSkin/blob/b1e5b999b2464808f61efca26890406f4595e26a/resources/variables.less#L11-L13

구체적으로 글로벌 font-family 설정 중 맑은 고딕과 돋움이 방해를 하고 있습니다. lang=ja를 위한 font-family 설정을 따로 넣거나 또는 글로벌 설정에 있는 글꼴 목록을 최소화했으면 합니다.

**Comment by saschanaz** [comment]
예를 들어 트위터 웹은 한국어 트윗에 대해 다음과 같이 설정합니다:

```CSS
.r-1qd0xha {
	font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, Helvetica, Arial, sans-serif;
}
```

이렇게 하면 최대한 사용자가 설정한 시스템 글꼴 설정을 사용하도록 만들 수 있습니다.
