### ISSUE TITLE
Progressive button on OOUI dialog has a padding

### ISSUE THREAD

**Issue by lens0021** [femiwiki/FemiwikiSkin#295]
![image](https://user-images.githubusercontent.com/28209361/127451613-a9e2ce16-3570-4b7e-ad1c-53763c4318df.png)

**Comment by lens0021** [comment]
The next rule is needed (it's for Vector)

```css
.ve-ui-overlay-global {
	/* Same as main content font-size in Vector */
	font-size: 0.875em;
}
```

https://github.com/wikimedia/mediawiki-extensions-VisualEditor/blob/9c0b4cfa93c7691fe8ff9f0e827cdc6adc120a3d/modules/ve-mw/init/styles/ve.init.mw.DesktopTarget-vector.css#L18-L21
