### ISSUE TITLE
어두운 모드를 활성화하면 "관련 항목" 부분 색상이 반전됨

### ISSUE THREAD

**Issue by saschanaz** [femiwiki/FemiwikiSkin#415]
![image](https://user-images.githubusercontent.com/3396686/147608017-75c07591-4a4a-4369-9efa-ca1223db4f8c.png)

```css
.client-dark-mode .ext-related-articles-card-thumb {
  filter: invert(1) hue-rotate(180deg);
  background-color: transparent;
}
```

위 코드를 추가하면 고쳐집니다.
